<?php

/**
 * @file
 * Contains quick_clone.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function quick_clone_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the quick_clone module.
    case 'help.page.quick_clone':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module wich allow cloning nodes with paragarph fields') . '</p>';
      return $output;

    default:
  }
}

/**
 * Helping function.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   Entity which will be linked for cloning.
 *
 * @return array
 *   An operations array as returned by
 *   EntityListBuilderInterface::getOperations().
 *
 * @see \Drupal\Core\Entity\EntityListBuilderInterface::getOperations()
 */
function quick_clone_entity_operation(EntityInterface $entity) {

  $operations = [];

  if ($entity instanceof Node) {
    $operations['clone'] = [
      'title' => t('Clone'),
      'url' => Url::fromRoute('quick_clone', ['id' => $entity->id()]),
      'weight' => 150,
    ];
  }

  return $operations;
}
